# 实现全连接

In [1]:
import torch
from torch import nn

In [2]:
class Liner(nn.Module):
    def __init__(self, in_features, out_features):
        super(Liner, self).__init__()
        self.w = nn.Parameter(torch.randn(in_features, out_features)) #nn.Parameter默认的requires_grad=True
        self.b = nn.Parameter(torch.randn(out_features))
        
    def forward(self, x):
        return x.mm(self.w) + self.b #必须用mm，矩阵运算，*是对所有元素进行运算

In [3]:
layer = Liner(4, 3)
inputs = torch.randn((2,4), requires_grad = True)
output = layer(inputs) #直接调用layer(input)，不用layer.forward(input)
output

tensor([[-0.5586,  1.1560,  0.2749],
        [ 2.1434, -0.9755,  1.1023]], grad_fn=<AddBackward0>)

In [4]:
for i in layer.parameters(): #获取参数
    print(i)

Parameter containing:
tensor([[ 0.6407, -0.0551,  0.0428],
        [-0.2619,  1.4375, -0.7751],
        [ 1.0167, -0.5471, -0.0039],
        [-0.2408,  0.0442, -0.3783]], requires_grad=True)
Parameter containing:
tensor([-0.6660,  0.7761,  0.8841], requires_grad=True)


In [5]:
for name, param in layer.named_parameters():
    print(name)
    print("---------------------------------------")
    print(param)

w
---------------------------------------
Parameter containing:
tensor([[ 0.6407, -0.0551,  0.0428],
        [-0.2619,  1.4375, -0.7751],
        [ 1.0167, -0.5471, -0.0039],
        [-0.2408,  0.0442, -0.3783]], requires_grad=True)
b
---------------------------------------
Parameter containing:
tensor([-0.6660,  0.7761,  0.8841], requires_grad=True)


# 多层感知机

In [6]:
class Perceptron(nn.Module):
    def __init__(self, in_feature, hidden_feature, out_feature):
        super().__init__()
        self.layer1 = Liner(in_feature, hidden_feature) #Liner中的可学习参数也会成为当前类的可学习参数
        self.layer2 = Liner(hidden_feature, out_feature)
    def forward(self, x):
        x = nn.Sigmoid(self.layer1(x))
        x = self.layer2(x)
        return x

包含子类时的命名方法：

self.sub_module = SubModule(); SubModule中有parameter为para_name

则最终的name为：sub_module.para_name

In [7]:
perceptron = Perceptron(3, 4, 1)
for name, param in perceptron.named_parameters(): 
    print(name,":",param.size())

layer1.w : torch.Size([3, 4])
layer1.b : torch.Size([4])
layer2.w : torch.Size([4, 1])
layer2.b : torch.Size([1])
