# RCNN--LSTM

输入数据格式：

input(seq_len, batch, input_size)

h0(num_layers * num_directions, batch, hidden_size)

c0(num_layers * num_directions, batch, hidden_size)

输出数据格式：

output(seq_len, batch, hidden_size * num_directions)

hn(num_layers * num_directions, batch, hidden_size)

cn(num_layers * num_directions, batch, hidden_size)

In [1]:
import torch
import torch.nn as nn

torch.manual_seed(1000)

inputs = torch.randn(2, 3, 4) #(seq_len, batch, input_size)


lstm1 = nn.LSTM(4, 3, 1) #(input_size,hidden_size,num_layers)
c0 = torch.randn(1, 3, 3) #(num_layers,batch,output_size)

h0 = torch.randn(1, 3, 3) #(num_layers,batch,output_size)
out, (h, c) = lstm1(inputs, (h0, c0))

out

tensor([[[ 0.2414, -0.5002, -0.1329],
         [ 0.0371, -0.3382,  0.0037],
         [-0.1093, -0.1813,  0.1471]],

        [[ 0.3509, -0.1424, -0.2893],
         [ 0.2316, -0.1697, -0.1579],
         [-0.0998, -0.4573,  0.1646]]], grad_fn=<StackBackward>)

In [2]:
torch.manual_seed(1000)
inputs = torch.randn(2, 3, 4) #(seq_len, batch, input_size)

#一个LSTMCell对应的层数只是一层
lstm = nn.LSTMCell(4, 3) #(input_size,hidden_size)
cx = torch.randn(3, 3)
hx = torch.randn(3, 3)
out = []

for i in inputs:
    hx, cx = lstm(i, (hx, cx))
    out.append(hx)
torch.stack(out)


tensor([[[ 0.2414, -0.5002, -0.1329],
         [ 0.0371, -0.3382,  0.0037],
         [-0.1093, -0.1813,  0.1471]],

        [[ 0.3509, -0.1424, -0.2893],
         [ 0.2316, -0.1697, -0.1579],
         [-0.0998, -0.4573,  0.1646]]], grad_fn=<StackBackward>)

## 词向量在自然语言中也有非常广泛的应用，Pytorch同样也提供了Embedding层

In [3]:
embedding = nn.Embedding(4, 5)
#使用预训练好的词向量初始化embedding
embedding.weight.data = torch.arange(20).view(4, 5)

In [4]:
inputs = torch.arange(3, 0, -1).long()
inputs

tensor([3, 2, 1])

In [5]:
output = embedding(inputs)
output

tensor([[15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9]], grad_fn=<EmbeddingBackward>)

# 损失函数

In [6]:
score = torch.randn(3, 2)

label = torch.tensor([1, 0, 1])

criterion = nn.CrossEntropyLoss()
loss = criterion(score, label)

loss

tensor(0.5944)