# Tensor
pytorch的Tensor和numpy的ndarrays很像，所不同的是Tensor可以用GPU加速

从接口角度讲，对Tensor的操作可以分为两类：
1. torch.function
2. tensor.fuction

大部分Tensor同时支持这两种接口，如torch.sum(a, b)和a.sum(b)等价

从存储角度讲，对Tensor的操作又可以分为两类：
1. 不会修改自身数据，如a.add(b)
2. 会修改自身数据，如a.add_(b)

函数名以_结尾都是inplace方式

## 新建Tensor

In [1]:
import torch

In [2]:
a = torch.Tensor(2,3)
a

tensor([[1.6751e-37, 1.6119e+22, 2.7045e-43],
        [0.0000e+00, 7.0707e-16, 4.5806e-41]])

In [3]:
a = torch.Tensor((2,3)) #多一层括号
a

tensor([2., 3.])

In [4]:
a = torch.tensor([2,3]) #将内容转换为tensor
a

tensor([2, 3])

## 将tensor与list互换

In [5]:
b = torch.Tensor([[1,2,3],[4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.tolist() #不会对b进行修改

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [7]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 返回size

In [8]:
b_size = b.size()
b_size

torch.Size([2, 3])

In [9]:
b.numel() #返回元素总数

6

In [10]:
b.nelement() #等价

6

In [11]:
c = torch.Tensor(b_size)
c

tensor([[7.0708e-16, 4.5806e-41, 7.0708e-16],
        [4.5806e-41, 4.4842e-44, 0.0000e+00]])

tensor.shape与tensor.size()等价

In [12]:
c.shape

torch.Size([2, 3])

## 其他方法创建Tensor

In [13]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.arange(2,12,2)

tensor([ 2,  4,  6,  8, 10])

In [16]:
torch.linspace(1,10,3) #等分

tensor([ 1.0000,  5.5000, 10.0000])

In [17]:
torch.rand(2,3) #均匀分布

tensor([[0.5010, 0.0256, 0.9749],
        [0.1890, 0.9096, 0.9545]])

In [18]:
torch.randn(2,3) #标准分布

tensor([[-2.2236,  0.2427, -1.5575],
        [-0.1140, -1.8165, -0.2653]])

In [19]:
torch.randperm(5) #长度为5的随机排列

tensor([0, 3, 1, 2, 4])

In [20]:
torch.eye(2,3) #对角线为1

tensor([[1., 0., 0.],
        [0., 1., 0.]])

# 常用操作

## tensor.view
必须保存前后的元素数一致

In [21]:
a = torch.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [22]:
b = a.view(2,3) #新的Tensor与原Tensor共享内存
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [23]:
a[1] = 100
a

tensor([  0, 100,   2,   3,   4,   5])

In [24]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

## tensor.unsqueeze(dim)&tensor.squeeze(dim)

In [25]:
b.unsqueeze_(1) #增加维度
b.shape

torch.Size([2, 1, 3])

In [26]:
c = b.view(1,1,1,2,3)
c.shape

torch.Size([1, 1, 1, 2, 3])

In [27]:
c.squeeze_(0) #压缩第0维
c.shape

torch.Size([1, 1, 2, 3])

In [28]:
c.squeeze_() #压缩所有维度为1
c.shape

torch.Size([2, 3])

## tensor.resize()
元素数可以不一致，若超出，会分配新的空间；若不足，则会保存之前的旧数据

In [29]:
c

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [30]:
c.resize_(1,3)

tensor([[  0, 100,   2]])

In [31]:
c.resize_(3,3)

tensor([[                  0,                 100,                   2],
        [                  3,                   4,                   5],
        [4189032028197581669, 7005686999778735650, 3544671789880716601]])

## 索引

In [32]:
a = torch.randn(3, 4)
a

tensor([[-1.1687,  0.0252,  0.4010,  0.8814],
        [-0.8312, -0.7266,  1.6070,  0.6753],
        [-0.6873,  0.3415, -0.6421,  0.8420]])

In [33]:
a[0] #第0行

tensor([-1.1687,  0.0252,  0.4010,  0.8814])

In [34]:
a[:,0] #0列

tensor([-1.1687, -0.8312, -0.6873])

In [35]:
a[0][0] #元素

tensor(-1.1687)

In [36]:
a[0,0]

tensor(-1.1687)

In [37]:
a[0, -1] #0行最后一个元素

tensor(0.8814)

In [38]:
a[:2] #前两行

tensor([[-1.1687,  0.0252,  0.4010,  0.8814],
        [-0.8312, -0.7266,  1.6070,  0.6753]])

In [39]:
a[:2, :2] #前两行前两列

tensor([[-1.1687,  0.0252],
        [-0.8312, -0.7266]])

注意这两种方法shape不同

In [40]:
print(a[0:1, :2]) #(1,2)
print(a[0, :2]) #(2)

tensor([[-1.1687,  0.0252]])
tensor([-1.1687,  0.0252])


In [41]:
a>1

tensor([[False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]])

In [42]:
a[a>1]

tensor([1.6070])

In [43]:
a.masked_select(a>1)

tensor([1.6070])

In [44]:
a[torch.LongTensor([0,1])] #第0行和1行

tensor([[-1.1687,  0.0252,  0.4010,  0.8814],
        [-0.8312, -0.7266,  1.6070,  0.6753]])

In [45]:
torch.LongTensor([0,1]) #上一行相当于a[[0,1]]

tensor([0, 1])

In [46]:
a[[0,1]] #第0行和1行

tensor([[-1.1687,  0.0252,  0.4010,  0.8814],
        [-0.8312, -0.7266,  1.6070,  0.6753]])

## 常用的选择函数

In [47]:
a.index_select(1,torch.tensor([0,2])) #第0列和第2列

tensor([[-1.1687,  0.4010],
        [-0.8312,  1.6070],
        [-0.6873, -0.6421]])

In [48]:
a.index_select(0,torch.tensor([0,2])) #第0行和2行

tensor([[-1.1687,  0.0252,  0.4010,  0.8814],
        [-0.6873,  0.3415, -0.6421,  0.8420]])

In [49]:
a.masked_select(a>1) #根据ByteTensor进行选择，返回一维

tensor([1.6070])

In [50]:
a.nonzero() #返回非0元素下标

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3]])

#### gather
gather(input, dim, index) 根据index，在dim上选取数据，输出的size与index相同

dim为tensor数据类型

index：其维度有限定，例如当dim=i时，index的维度为（x1, x2, …y, …,xn），既是将input的第i维的大小更改为y，且要满足y>=1（除了第i维之外的其他维度，大小要和input保持一致）

In [51]:
a = torch.arange(0,16.0).view(4,4)
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [52]:
# 选取对角线元素
a.gather(0, torch.tensor([[0,1,2,3]])) #[1,4]

tensor([[ 0.,  5., 10., 15.]])

In [53]:
a.gather(1, torch.tensor([[0],[1],[2],[3]])) #[4,1]

tensor([[ 0.],
        [ 5.],
        [10.],
        [15.]])

In [54]:
# 选取反对角线元素
a.gather(0, torch.tensor([[3,2,1,0]]))

tensor([[12.,  9.,  6.,  3.]])

In [55]:
a.gather(1, torch.tensor([[3],[2],[1],[0]]))

tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])

In [56]:
#选取两个对角线元素
a.gather(0, torch.tensor([[0,1,2,3],[3,2,1,0]]))

tensor([[ 0.,  5., 10., 15.],
        [12.,  9.,  6.,  3.]])

In [57]:
a.gather(1, torch.tensor([[0,3],[1,2],[2,1],[3,0]]))#[4,2]

tensor([[ 0.,  3.],
        [ 5.,  6.],
        [10.,  9.],
        [15., 12.]])

#### scatter_
为gather的逆操作

In [58]:
b = a.gather(1, torch.tensor([[0,3],[1,2],[2,1],[3,0]]))
b

tensor([[ 0.,  3.],
        [ 5.,  6.],
        [10.,  9.],
        [15., 12.]])

In [59]:
c = torch.zeros(4,4)
c

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
c.scatter_(1, torch.tensor([[0,3],[1,2],[2,1],[3,0]]), b)
c

tensor([[ 0.,  0.,  0.,  3.],
        [ 0.,  5.,  6.,  0.],
        [ 0.,  9., 10.,  0.],
        [12.,  0.,  0., 15.]])

## 高级索引

In [61]:
x = torch.arange(0,27).view(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [62]:
x[1,1,1]

tensor(13)

In [63]:
x[[1,2],[0,1],[2,0]] #x[1,0,2],x[2,1,0]

tensor([11, 21])

In [64]:
x[[2,0,1],0,1] #x[2,0,1],x[0,0,1], x[1,0,1]

tensor([19,  1, 10])

In [65]:
x[[0,2],...] #x[0], x[2]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [66]:
x[[2,0],[1,0],...] #x[2,1], x[0,0]

tensor([[21, 22, 23],
        [ 0,  1,  2]])

## 数据类型
Tensor有不同种的数据类型，每种类型都有CPU和GPU两种。如：torch.FloatTensor和torch.cuda.FloatTensor.

可以通过torch.set_default_tensor_type修改默认的数据类型

16bit半精度浮点数torch.cuda.HalfTensor是专门为gpu设计的，缓解现存问题。

torch.FloatTensor, torch.DoubleTensor, torch.cuda.HalfTensor, torch.ByteTensor(8bit无符号整型)， torch.CharTensor(8bit有符号整形), torch.ShortTensor, torch.IntTensor, torch.LongTensor

数据类型之间互相转换：type(new_type)是通用的做法，还有float、long、half等方法

CPU tensor和GPU tensor之间的转换可以通过 tensor.cuda和tensor.cpu来实现

In [67]:
torch.set_default_tensor_type('torch.FloatTensor')

In [68]:
a = torch.Tensor(2,3)
a

tensor([[ 7.0708e-16,  4.5806e-41, -4.8379e-35],
        [ 3.0805e-41,  4.4842e-44,  0.0000e+00]])

In [69]:
b = a.type(torch.IntTensor)
b

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [70]:
b = a.int()
b

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [71]:
c = b.type_as(a) #将b的数据类型转换为a的数据类型
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [72]:
d = b.new(3,4) #和b同数据类型
d

tensor([[642502032,     32688, 642502032,     32688],
        [      176,         0,       112,         0],
        [        0,         0,        64,         0]], dtype=torch.int32)

## 逐元素操作
abs, sqrt, div, exp, fmod, log, pow

cos, sin, asin, atan2, cosh

ceil, round, floor, trunc(只保留整数部分)

clamp(input, min, max)

sigmoid、tanh等激活函数都是逐元素操作

In [73]:
torch.set_default_tensor_type('torch.FloatTensor')

In [74]:
a = torch.arange(0,6.0).view(2,3)
torch.cos(a)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])

In [75]:
a % 3 #等价于torch.fmod(a,3)

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [76]:
torch.fmod(a,3)

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [77]:
a ** 2 #torch.pow(a, 2)

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [78]:
torch.clamp(a, 1, 3) #若元素小于min，取min；大于max，取max；否则取a

tensor([[1., 1., 2.],
        [3., 3., 3.]])

## 归并操作
mean, median, sum, mode(众数)

norm(范数), dist(距离)

std(标准差), var(方差)

cumsum(累加)，cumprod(累乘)

假设输入形状为(m, n, k)：

若dim = 0：输出为（1, n, k）或(n, k)

若dim = 1：输出为（m, 1, k）或(m, k)

若dim = 0：输出为（m, n, 1）或(m, n)

In [79]:
b = torch.ones(2,3)
print(b)
b.sum(0) #默认keepdim = False

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([2., 2., 2.])

In [80]:
b.sum(0, keepdim = True)

tensor([[2., 2., 2.]])

In [81]:
b.sum(1)

tensor([3., 3.])

In [82]:
b.sum(1, keepdim = True)

tensor([[3.],
        [3.]])

In [83]:
a = torch.arange(0,6).view(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [84]:
a.cumsum(1) #沿行累加

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

In [85]:
a.cumsum(0) #沿列累加

tensor([[0, 1, 2],
        [3, 5, 7]])

## 比较
|比较|
|---|
|gt/lt/ge/le/eq/ne|
|topk|
|sort|
|max/min|

In [86]:
a = torch.linspace(0, 15, 6).view(2, 3)
a

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])

In [87]:
b = torch.linspace(15, 0, 6).view(2, 3)
b

tensor([[15., 12.,  9.],
        [ 6.,  3.,  0.]])

In [88]:
a>b

tensor([[False, False, False],
        [ True,  True,  True]])

In [89]:
torch.gt(a, b)

tensor([[False, False, False],
        [ True,  True,  True]])

In [90]:
a.gt(b)

tensor([[False, False, False],
        [ True,  True,  True]])

In [91]:
a[a>b] #取a>b的元素

tensor([ 9., 12., 15.])

In [92]:
torch.max(a)

tensor(15.)

In [93]:
torch.max(a, dim=1) #return values & index

torch.return_types.max(
values=tensor([ 6., 15.]),
indices=tensor([2, 2]))

In [94]:
torch.max(a, dim=0) #当指定dim时，会返回index

torch.return_types.max(
values=tensor([ 9., 12., 15.]),
indices=tensor([1, 1, 1]))

## 线性代数

|操作内容|
|:---:|:---:|:---:|
|trace:对角线元素求和|    diag：对角线元素|     triu/tril:矩阵的上三角和下三角|
|mm/bmm:矩阵乘法，batch的矩阵乘法|    addmm/addbmm/addmv:矩阵运算|     t：转置|
|dot/cross:内积，外积|    inverse:求逆矩阵|    svd：奇异值分解|

In [95]:
b = a.t()
b

tensor([[ 0.,  9.],
        [ 3., 12.],
        [ 6., 15.]])

In [96]:
b.is_contiguous() #转置会导致存储空间不连续

False

In [100]:
b.contiguous() #???仍然不连续
b.is_contiguous()

False